-- Supabase setup script for Meu Mercadin™

-- 1. Create the table to store shopping lists
CREATE TABLE public.shopping_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text,
  items jsonb,
  members jsonb,
  -- Optional: Add a user_id foreign key if you want to link lists to a specific owner
  user_id uuid REFERENCES auth.users(id)
);

-- 2. Enable Row Level Security (RLS)
-- This ensures that users can only access data they are permitted to.
ALTER TABLE public.shopping_lists ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow authenticated users to create new lists
CREATE POLICY "Allow insert for authenticated users"
ON public.shopping_lists
FOR INSERT TO authenticated
WITH CHECK (true);

-- 4. Create a policy to allow members of a list to view it
-- This policy checks if the authenticated user's ID is present in the 'members' JSONB array.
-- Note: This assumes the user's ID is stored in the 'id' field within the JSON object.
-- Supabase's auth.uid() returns a UUID, so we cast it to text for comparison.
CREATE POLICY "Allow select for members"
ON public.shopping_lists
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1
    FROM jsonb_array_elements(members) AS elem
    WHERE elem->>'id' = auth.uid()::text
  )
);

-- =============================================================================
-- == VERIFICATION SCRIPT
-- == Run this script to check if the tables and policies were created correctly.
-- == This script is read-only and does not make any changes.
-- =============================================================================

-- Part 1: Verify Tables and RLS Status
-- Should list the 3 tables and confirm that RLS is "Enabled" for all.
SELECT
    c.relname AS table_name,
    CASE WHEN c.relrowsecurity THEN 'Enabled' ELSE 'Disabled' END AS rls_status
FROM
    pg_catalog.pg_class c
JOIN
    pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE
    n.nspname = 'public' AND c.relkind = 'r' -- 'r' for regular tables
    AND c.relname IN ('shopping_lists', 'categories', 'products')
ORDER BY
    c.relname;

-- Part 2: List all applied Security Policies
-- Should list all the policies we created in this file, showing which table
-- they apply to and for which command (SELECT, INSERT, etc.).
SELECT
    policyname AS policy_name,
    schemaname AS schema_name,
    tablename AS table_name,
    cmd AS command,
    qual AS using_clause,
    with_check AS with_check_clause
FROM
    pg_policies
WHERE
    schemaname = 'public'
    AND tablename IN ('shopping_lists', 'categories', 'products')
ORDER BY
    table_name, policy_name;

-- =============================================================================
-- 7. Create the table for categories
CREATE TABLE public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  user_id uuid DEFAULT auth.uid() REFERENCES auth.users(id)
);

-- 8. Enable RLS for categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 9. Policies for categories
CREATE POLICY "Allow read for authenticated users" ON public.categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.categories FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for owners" ON public.categories FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "Allow delete for owners" ON public.categories FOR DELETE USING (user_id = auth.uid());

-- 10. Create the table for preset products
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text,
  unit text,
  user_id uuid DEFAULT auth.uid() REFERENCES auth.users(id)
);

-- 11. Enable RLS for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 12. Policies for products
CREATE POLICY "Allow read for authenticated users" ON public.products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert for authenticated users" ON public.products FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for owners" ON public.products FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "Allow delete for owners" ON public.products FOR DELETE USING (user_id = auth.uid());

-- 5. Create a policy to allow members of a list to update it
CREATE POLICY "Allow update for members"
ON public.shopping_lists
FOR UPDATE TO authenticated USING (
  EXISTS (
    SELECT 1
    FROM jsonb_array_elements(members) AS elem
    WHERE elem->>'id' = auth.uid()::text
  )
);

-- 6. Create a policy to allow members of a list to delete it
CREATE POLICY "Allow delete for members"
ON public.shopping_lists
FOR DELETE TO authenticated USING (
  EXISTS (
    SELECT 1
    FROM jsonb_array_elements(members) AS elem
    WHERE elem->>'id' = auth.uid()::text
  )
);
